# tab bar configuration
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled
tab_activity_symbol ⚡
tab_bar_background #444

# colors
background #1c1c1c

# os specific tweaks
linux_display_server auto

# window layout
enabled_layouts splits:split_axis=horizontal

## keyboard shortcuts
map F1 launch --location=hsplit
map F2 launch --location=vsplit
map F3 layout_action rotate

map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

map ctrl+left resize_window narrower 3
map ctrl+right resize_window wider 3
map ctrl+up resize_window taller 3
map ctrl+down resize_window shorter 3
