# Main Hyprland config entrypoint
source = ~/.config/hypr/theme-mocha.conf
source = ~/.config/hypr/conf/variables.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/keybinds.conf
