[mgr]
ratio = [1, 2, 5] # Example: Parent: 1, Current: 4, Preview: 3
show_hidden = false
show_symlink = true
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
linemode = "size"
scrolloff = 5
mouse_events = ["click", "scroll", "touch"]
title_format = "Yazi: {cwd}"

[preview]
image_delay = 30
image_filter = "lanczos3"
image_quality = 90

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "open" },
  { mime = "video/*", use = "open" },
]
