# Execute your favorite apps at launch
#exec-once = ~/.config/hypr/scripts/xdg-portal-hyprland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = ~/.config/hypr/scripts/gtk-theme.sh
exec-once = $bar
exec-once = $notification
exec-once = dropbox
exec-once = hyprpaper
exec-once = wl-paste --type text --watch cliphist -max-items 10 store
exec-once = hypridle
exec-once = blueman-applet
exec-once = elephant
exec-once = walker --gapplication-service
