local programs = require("conf/variables")

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("$HOME/.config/hypr/scripts/gtk-theme.sh")
    hl.exec_cmd(programs.bar)
    hl.exec_cmd(programs.notification)
    hl.exec_cmd("dropbox")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("wl-paste --type text --watch cliphist -max-items 10 store")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("elephant")
    hl.exec_cmd("walker --gapplication-service")
end)
