# Input devices
input {
    kb_layout    = us
    kb_variant   = altgr-intl
    kb_model     =
    # kb_options = caps:swapescape
    kb_rules     =
    repeat_delay = 600
    repeat_rate  = 35
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
    sensitivity  = 0  # -1.0 - 1.0, 0 means no modification.
}

# Expert Trackball Mouse
# note: you can use `libinput debug-events` to get the button numbers
device {
    name          = kensington-expert-wireless-tb-mouse
    #sensitivity  = -0.9
    accel_profile = adaptive
    scroll_method = on_button_down
    scroll_button = 275
}

# Logitech Lift mouse
device {
    name        = logitech-usb-receiver-mouse
    sensitivity = -0.4
}
