# Key bindings
bind = $mod, RETURN, exec, $terminal
bind = $mod SHIFT, q, killactive,
bind = $mod SHIFT, E, exit,
bind = $mod SHIFT, RETURN, exec, brave
bind = $mod, SPACE, togglefloating,
bind = $mod, d, exec, $menu
#bind = $mod, p, pseudo, # dwindle
bind = $mod, s, layoutmsg, togglesplit
bind = $mod, f, fullscreen
bind = $mod, ESCAPE, workspace, previous
bind = $mod, v, exec, walker -s clipboard

# Move focus with $mod + hjkl
bind = $mod, l, movefocus, r
bind = $mod, h, movefocus, l
bind = $mod, k, movefocus, u
bind = $mod, j, movefocus, d

# Switch workspaces with $mod + [0-9]
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# move active window to a workspace with $mod + shift + [0-9]
bind = $mod SHIFT, 1, movetoworkspacesilent, 1
bind = $mod SHIFT, 2, movetoworkspacesilent, 2
bind = $mod SHIFT, 3, movetoworkspacesilent, 3
bind = $mod SHIFT, 4, movetoworkspacesilent, 4
bind = $mod SHIFT, 5, movetoworkspacesilent, 5
bind = $mod SHIFT, 6, movetoworkspacesilent, 6
bind = $mod SHIFT, 7, movetoworkspacesilent, 7
bind = $mod SHIFT, 8, movetoworkspacesilent, 8
bind = $mod SHIFT, 9, movetoworkspacesilent, 9
bind = $mod SHIFT, 0, movetoworkspacesilent, 10

# Print screen
bind = $mod SHIFT, p, exec, $screenshot
bind = $mod, p, exec, $swappy
#bind = $mod, p, exec, $flameshot

# Scroll through existing workspaces with $mod+[SHIFT] + TAB
bind = $mod, TAB, workspace, e+1
bind = $mod SHIFT, TAB, workspace, e-1

# Move windows position with $mod + SHIFT + hjkl
bind = $mod SHIFT, l, movewindow,r
bind = $mod SHIFT, h, movewindow,l
bind = $mod SHIFT, k, movewindow,u
bind = $mod SHIFT, j, movewindow,d

# idle
bindr = $mod SHIFT, l, exec, loginctl lock-session

# volume control
binde = , XF86AudioRaiseVolume, exec, $volume_up
binde = , XF86AudioLowerVolume, exec, $volume_down
bind = , XF86AudioMute, exec, $volume_mute

# brightness control
bindl = , XF86MonBrightnessUp, exec, $brightness_up
bindl = , XF86MonBrightnessDown, exec, $brightness_down

# Move/resize windows with $mod + mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# resize window with $mod + R
# will switch to a submap called resize
bind = $mod, R, submap, resize
# will start a submap called "resize"
submap = resize
# sets repeatable binds for resizing the active window
binde = , h, resizeactive, -15 0
binde = , l, resizeactive, 15 0
binde = , k, resizeactive, 0 -15
binde = , j, resizeactive, 0 15
# use ESCAPE key to go back to the global submap
bind = , ESCAPE, submap, reset
bind = $mod, R, submap, reset
# will reset the submap, meaning end the current one and return to the global one
submap = reset

#close/open lid event
bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1,preferred,2560x0,1"

# Monitor toggle on/off
bind = SUPER, minus, exec, ~/.config/hypr/scripts/laptop_display_toggle.sh eDP-1
bind = SUPER, equal, exec, ~/.config/hypr/scripts/laptop_display_toggle.sh HDMI-A-1

# plugin
#bind = SUPER, grave, hyprexpo:expo, toggle # can be: toggle, off/disable or on/enable
