# Variable definitions
$mod = SUPER
$terminal = kitty
#$menu = fuzzel --show drun
$menu = walker
$notification = mako
$bar = waybar
$screenshot = grim -g "$(slurp)" ~/Pictures/$(date +%F_%H-%M-%S).png
$swappy = grim -g "$(slurp)" - | swappy -f -
$flameshot = XDG_CURRENT_DESKTOP=sway flameshot gui
$onscreen_bar = bash $HOME/.config/sway/scripts/wob.sh
$sink_volume = pactl get-sink-volume @DEFAULT_SINK@ | grep '^Volume:' | cut -d / -f 2 | tr -d ' ' | sed 's/%//'
$source_volume = pactl get-source-volume @DEFAULT_SOURCE@ | grep '^Volume:' | cut -d / -f 2 | tr -d ' ' | sed 's/%//'
$volume_down = $onscreen_bar $(pactl set-sink-volume @DEFAULT_SINK@ -5% && $sink_volume)
$volume_up = $onscreen_bar $(pactl set-sink-volume @DEFAULT_SINK@ +5% && $sink_volume)
$volume_mute = $onscreen_bar $(pactl set-sink-mute @DEFAULT_SINK@ toggle && pactl get-sink-mute @DEFAULT_SINK@ | sed -En "/no/ s/.*/$($sink_volume)/p; /yes/ s/.*/0/p")
$mic_mute = $onscreen_bar $(pactl set-source-mute @DEFAULT_SOURCE@ toggle && pactl get-source-mute @DEFAULT_SOURCE@ | sed -En "/no/ s/.*/$($source_volume)/p; /yes/ s/.*/0/p")
$wallpaper = ~/.config/backgrounds/desktop-background

# brightness control
$brightness_step = bash -c 'echo $(( $(light -Mr) / 100 * 5 < 1 ? 1 : $(( $(light -Mr) / 100 * 5 )) ))'
$brightness_up = light -r -A $($brightness_step) && $onscreen_bar $(light -G | cut -d'.' -f1)
$brightness_down = light -r -U $($brightness_step) && $onscreen_bar $(light -G | cut -d'.' -f1)
