# Window rules

# Kitty for Waybar window
windowrule {
  name = windowrule-1
  float = on
  size = (monitor_w*0.5) (monitor_h*0.7)
  center = on
  match:class = ^(floating_shell)$
}

# Open Files window
windowrule {
  name = windowrule-2
  float = on
  size = (monitor_w*0.6) (monitor_h*0.9)
  match:title = (Open Files|Save File)
}

windowrule {
  name = windowrule-3
  center = on
  match:title = Open Files
}

# Annoying Google Meet window
windowrule {
  name = windowrule-4
  workspace = 10 silent
  match:initial_title = (Meet - .*)
}
